version: '3.3'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotelbooking
    ports:
      - "3306:3306"
    volumes:
      - ./init_sql:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
