version: '3.3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-seeder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongo-seeder
    depends_on:
      - mongo
    command: python mongo_seeder.py

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    command: python app.py

volumes:
  mongo-data:
